name: Auto Update Submodules (Bot)

on:
  schedule:
    - cron: "0 3 * * *"   # Setiap hari jam 03:00 UTC
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Configure Git as Bot
        run: |
          git config user.name  "QueenofLoveandHate"
          git config user.email "queenofloveandhate@gmail.com"

      - name: Update all submodules
        run: |
          git submodule update --remote --recursive

      - name: Check for changes
        id: changes
        run: |
          if git status --porcelain | grep .; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit submodule updates
        if: steps.changes.outputs.changed == 'true'
        run: |
          git add .
          git commit -m "chore(submodule): auto update"

      - name: Push changes using bot
        if: steps.changes.outputs.changed == 'true'
        run: |
          git push https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
